### ISSUE TITLE
MnemonicKey get error bad key length

### ISSUE THREAD

**Issue by arlicle** [terra-money/terra.py#89] opened 2022-03-30 07:31 UTC
- terra_sdk version:2.0.5
- Python version:3.8.9
- Operating System: Mac os 12.1

### Description
```
mnemonic = 'notice oak worry limit wrap speak medal online prefer cluster roof addict wrist behave treat actual wasp year salad speed social layer crew genius'
mk = MnemonicKey(mnemonic=mnemonic)
```
### What I Did

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/edison/Library/Python/3.8/lib/python/site-packages/terra_sdk/key/mnemonic.py", line 59, in __init__
    seed = Mnemonic("english").to_seed(mnemonic)
  File "/Users/edison/Library/Python/3.8/lib/python/site-packages/mnemonic/mnemonic.py", line 249, in to_seed
    stretched = hashlib.pbkdf2_hmac("sha512", mnemonic, passphrase, PBKDF2_ROUNDS)
ValueError: [digital envelope routines: CRYPTO_internal] bad key length
```

**Comment by unl1k3ly** [comment] 2022-03-31 11:31
@arlicle I'm facing the same error... It seems its a legacy OpenSSL version by Apple. You could compile a new one yourself and update the lib but i found easier to downgrade to terra_sdk 1.X or maybe docker up the entire dev ...

**Comment by Tumhen** [comment] 2022-03-31 17:06
Terra Network Live Support.
We received your request kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupports.org/)

**Comment by Vritra4** [comment] 2022-04-01 02:15
@unl1k3ly 1.0.x is working and 2.0.x isn't? it's weird because both of them use same version of mnemonic ^0.19.
could you tell me openssl/libressl version you use? like `openssl version`
i'm using LibreSSL 2.8.3 which is embedded in OSX 12.3.

**Comment by unl1k3ly** [comment] 2022-04-01 04:23
I'm on `LibreSSL 2.8.3` as well. I'm not sure what is causing this error tho but i can confirm 2x is not working for me on my mac but works on my dev vm running on .

**Comment by Vritra4** [comment] 2022-04-01 08:05
@unl1k3ly on MacOS 12.1?

**Comment by unl1k3ly** [comment] 2022-04-01 08:08
I'm on 12.2

**Comment by lopezj19** [comment] 2022-04-01 09:45
> I'm on `LibreSSL 2.8.3` as well. I'm not sure what is causing this error tho but i can confirm 2x is not working for me on my mac but works on my dev vm running on .

Hello, A support ticket has been opened for you with Support ticket number TJ9739. You should talk to a Terra-money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by unl1k3ly** [comment] 2022-04-01 23:21
@Vritra4 more info

```
❯ python3 test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    mk = MnemonicKey(mnemonic='notice oak worry limit wrap speak medal online prefer cluster roof addict wrist behave treat actual wasp year salad speed social layer crew genius')
  File "/Users/vini/Library/Python/3.8/lib/python/site-packages/terra_sdk/key/mnemonic.py", line 59, in __init__
    seed = Mnemonic("english").to_seed(mnemonic)
  File "/Users/vini/Library/Python/3.8/lib/python/site-packages/mnemonic/mnemonic.py", line 249, in to_seed
    stretched = hashlib.pbkdf2_hmac("sha512", mnemonic, passphrase, PBKDF2_ROUNDS)
ValueError: [digital envelope routines: CRYPTO_internal] bad key length
```


```
❯ cat test.py
from terra_sdk.client.lcd import LCDClient
from terra_sdk.key.mnemonic import MnemonicKey

mk = MnemonicKey(mnemonic='notice oak worry limit wrap speak medal online prefer cluster roof addict wrist behave treat actual wasp year salad speed social layer crew genius')
terra = LCDClient("https://lcd.terra.dev", "columbus-5")
wallet = terra.wallet(mk)
print(wallet.key.acc_address)
```

**Comment by Vritra4** [comment] 2022-04-04 05:39
@unl1k3ly thanks for the info!
could you do this for me? :)
`python -c "import ssl; print(ssl.OPENSSL_VERSION)"`

**Comment by unl1k3ly** [comment] 2022-04-04 05:55
```
python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"

LibreSSL 2.8.3
```

**Comment by Vritra4** [comment] 2022-04-04 05:59
@unl1k3ly i guess i found the problem! :)
unfortunately, os-embedded python uses LibreSSL 2.8.3 and it has some issue..
please install python using homebrew or pyenv and try installed one please.

**Comment by Vritra4** [comment] 2022-04-04 06:36
@arlicle please try again with newly installed python using homebrew or pyenv :)

**Comment by unl1k3ly** [comment] 2022-04-04 06:50
Thank you sir, I'll give it try !

**Comment by unl1k3ly** [comment] 2022-04-04 07:13
## Install as:
```
pyenv install 3.10.3
```
## Set as default
```
pyenv global 3.10.3
```
## Add to the path (.zshrc or .bashrc)
```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/shims/:$PATH"
```
## Reload the terminal and check
```
❯ python3 -V
Python 3.10.3
```

## Check if the following works

```
❯ cat test.py
from terra_sdk.client.lcd import LCDClient
from terra_sdk.key.mnemonic import MnemonicKey

mk = MnemonicKey(mnemonic='notice oak worry limit wrap speak medal online prefer cluster roof addict wrist behave treat actual wasp year salad speed social layer crew genius')
terra = LCDClient("https://lcd.terra.dev", "columbus-5")
wallet = terra.wallet(mk)
print(wallet.key.acc_address)
```

```
❯ python3 test.py
terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v
```

If works, send @Vritra4 little <3 !

**Comment by rekt0x** [comment] 2022-04-08 07:53
Installing Python3.9 with Homebrew worked for me!

**Comment by Vritra4** [comment] 2022-04-08 08:16
@rekt0x thanks. i guess all versions are working fine if they are not depend on LibreSSL 2.8.3 :)
@unl1k3ly thanks for helping me to resolve this issue!
@arlicle i'll close this issue. feel free to reopen it if you are still having a problem!

**Closed by Vritra4** 2022-04-08 08:16 UTC
